export const AccountArchive = (email) => {
  return (
    <div className="p-3">
      <main className="border shadow p-5">
        <div className="text-center">
          <h1 className="text-blue text-landing mb-0" style="font-weight: 900">
            TalkTherapy
          </h1>
          <h4>Speech service in your hands.</h4>
          <hr />
          <h5 className="text-center my-3">Account Archived</h5>
          <hr />
        </div>

        <div className="text-center">
          <p>
            Your account ${email} has been automatically archived by the system.
            This is due to inactivity for a period of time.
          </p>

          <p>
            If you wish to reactivate your account, please contact us at
            talktherapycapstone@gmail.com.
          </p>
        </div>

        <div className="text-center text-black-50" style="font-size: 0.75rem;">
          <p className="mb-0">
            This email is automatically generated by the TalkTherapy system.
          </p>
          <p>
            If you received this email by mistake please report it to
            talktherapycapstone@gmail.com or ignore.
          </p>
        </div>
      </main>
    </div>
  );
};
