export const Otp = (otp) => {
  return (
      <div className="p-3">
        <div className="border shadow p-5">
          <div className="text-center">
            <h1
              className="text-blue text-landing mb-0"
              style="font-weight: 900"
            >
              TalkTherapy
            </h1>
            <h4>Speech service in your hands.</h4>
            <hr />
            <h5 className="text-center my-3">OTP Forgot Password</h5>
            <hr />
          </div>
          text: `You are receiving this because you (or someone else) have
          <div className="text-center">
            <h4>${otp}.</h4>

            <p>
              You received this becaused you (or someone else) have requested
              the reset of the password for your TalkTherapy account.
            </p>

            <p>
              If you did not request this, please ignore this eamil and your
              password will remain unchanged.
            </p>
          </div>
          <div
            className="text-center text-black-50"
            style="font-size: 0.75rem;"
          >
            <p className="mb-0">
              This email is automatically generated by the TalkTherapy system.
            </p>
            <p>
              If you received this email by mistake please report it to
              talktherapycapstone@gmail.com or ignore.
            </p>
          </div>
        </div>
      </div>
  );
};
