export const route = {
  sudo: {
    fetch: "api/super-admin-slp/get-super-admin",
    edit: "api/super-admin-slp/edit-super-admin",
    password: "api/super-admin-slp/change-password",
    picture: "api/super-admin-slp/update-profile-picture",
    editAdmin: "api/super-admin-slp/edit-admin",
    getAllAdmins: "api/super-admin-slp/getAllAdmins",
    getAdminById: "api/super-admin-slp/getAdminById/",
    updateProfilePicture: "api/super-admin-slp/update-profile-picture",
    archiveUser: "api/super-admin-slp/archive-user",
    unarchiveUser: "api/super-admin-slp/unarchive-user",
    getArchivedAdmins: "api/super-admin-slp/get-archived-users",
  },
  admin: {
    addAdmin: "api/admin-slp/add-admin",
    removeAdmin: "api/admin-slp/remove-admin",
    activateAdmin: "api/admin-slp/activate-admin",
    signup: "api/admin-slp/admin-signup",
    fetch: "api/admin-slp/get-admin",
    getAllClinicians: "api/admin-slp/getAllClinicians",
    getClinicianById: "api/admin-slp/getClinicianById/",
    getAllPatients: "api/admin-slp/getAllPatients",
    getPatientById: "api/admin-slp/getPatientById/",
    edit: "api/admin-slp/edit-admin",
    password: "api/admin-slp/change-password",
    picture: "api/admin-slp/update-profile-picture",
    editClinician: "api/admin-slp/edit-clinician",
    editPatient: "api/admin-slp/edit-patient",
    pendingRequests: "api/admin-slp/pending-requests",
    updateRequestStatus: "api/admin-slp/update-request-status",
  },
  clinician: {
    addClinician: "api/clinician-slp/add-clinician",
    removeClinician: "api/clinician-slp/remove-clinician",
    activateClinician: "api/clinician-slp/activate-clinician",
    signup: "api/clinician-slp/signup",
    password: "api/clinician-slp/change-password",
    fetch: "api/clinician-slp/get-clinician",
    edit: "api/clinician-slp/edit-clinician",
    getAllPatients: "api/clinician-slp/getAllPatients",
    getPatientById: "api/clinician-slp/getPatientById/",
    picture: "api/clinician-slp/update-profile-picture",
    getAssignedPatients: "api/clinician-slp/get-assigned-patients",
    requestAccess: "api/clinician-slp/request-access",
  },
  patient: {
    deactivate: "api/patient-SLP/remove-slp-patient",
    activate: "api/patient-SLP/activate-slp-patient",
    signup: "api/patient-SLP/slp-patient-signup",
    fetch: "api/patient-SLP/get-patient",
    password: "api/patient-SLP/change-password",
    picture: "api/patient-SLP/update-profile-picture",
    edit: "api/patient-SLP/edit-patient",
    updateBookmarks: "api/patient-SLP/update-bookmarks",
  },
  system: {
    login: "api/super-admin-slp/login",
    forgot: "api/super-admin-slp/forgot-password",
    otp: "api/super-admin-slp/verify-otp",
    reset: "api/super-admin-slp/reset-password",
    audit: "api/super-admin-slp/audit-logs",
    email: "api/super-admin-slp/email-notification",
    getEmailAdmins: "api/super-admin-slp/email-admins",
  },
  appointment: {
    createFile: "api/appointments-slp/create-appointment/file",
    createJSON: "api/appointments-slp/create-appointment/json",
    getAll: "api/appointments-slp/get-all-appointments",
    get: "api/appointments-slp/get-appointment",
    edit: "api/appointments-slp/edit-appointment/:appointmentId",
    getById: "api/appointments-slp/get-appointment-by-id",
    updateStatus: "api/appointments-slp/update-status",
    getByClinician: "api/appointments-slp/get-appointment-by-clinician",
    requestScheduleChange: "api/appointments-slp/request-schedule-change",
    requestTemporaryReschedule:
      "api/appointments-slp/request-temporary-reschedule",
  },
  schedule: {
    create: "api/schedule-slp/add-schedule",
    get: "api/schedule-slp/get-schedules",
    getScheduleById: "api/schedule-slp/get-schedule",
    edit: "api/schedule-slp/edit-schedule",
    delete: "api/schedule-slp/delete-schedule",
    clinician: "api/schedule-slp/clinician-schedules",
  },
  soap: {
    create: "api/soap-slp/add-soap",
    edit: "api/soap-slp/edit-soap",
    delete: "api/soap-slp/delete-soap",
    getPatientSoap: "api/soap-slp/get-soap/",
    update: "api/soap-slp/edit-soap",
  },
  notification: {
    create: "api/notification-slp/create-notifications",
    get: "api/notification-slp/get-notifications"
  }
};
