export const route = {
  sudo: {
    fetch: "super-admin-slp/get-super-admin",
    edit: "super-admin-slp/edit-super-admin",
    password: "super-admin-slp/change-password",
    picture: "super-admin-slp/update-profile-picture",
    editAdmin: "super-admin-slp/edit-admin",
    getAllAdmins: "super-admin-slp/getAllAdmins",
    getAdminById: "super-admin-slp/getAdminById/",
    updateProfilePicture: "super-admin-slp/update-profile-picture",
  },
  admin: {
    addAdmin: "admin-slp/add-admin",
    removeAdmin: "admin-slp/remove-admin",
    activateAdmin: "admin-slp/activate-admin",
    signup: "admin-slp/admin-signup",
    fetch: "admin-slp/get-admin",
    getAllClinicians: "admin-slp/getAllClinicians",
    getClinicianById: "admin-slp/getClinicianById/",
    getAllPatients: "admin-slp/getAllPatients",
    getPatientById: "admin-slp/getPatientById/",
    edit: "admin-slp/edit-admin",
    password: "admin-slp/change-password",
    picture: "admin-slp/update-profile-picture",
    editClinician: "admin-slp/edit-clinician",
    editPatient: "admin-slp/edit-patient",
  },
  clinician: {
    addClinician: "clinician-slp/add-clinician",
    removeClinician: "clinician-slp/remove-clinician",
    activateClinician: "clinician-slp/activate-clinician",
    signup: "clinician-slp/signup",
    password: "clinician-slp/change-password",
    fetch: "clinician-slp/get-clinician",
    edit: "clinician-slp/edit-clinician",
    getAllPatients: "clinician-slp/getAllPatients",
    getPatientById: "clinician-slp/getPatientById/",
    picture: "clinician-slp/update-profile-picture",
  },
  patient: {
    deactivate: "patient-SLP/remove-slp-patient",
    activate: "patient-SLP/activate-slp-patient",
    signup: "patient-SLP/slp-patient-signup",
    fetch: "patient-SLP/get-patient",
    password: "patient-SLP/change-password",
    picture: "patient-SLP/update-profile-picture",
    edit: "patient-SLP/edit-patient",
  },
  system: {
    login: "super-admin-slp/login",
    forgot: "super-admin-slp/forgot-password",
    otp: "super-admin-slp/verify-otp",
    reset: "super-admin-slp/reset-password",
  },
  appointment: {
    createFile: "appointments-slp/create-appointment/file",
    createJSON: "appointments-slp/create-appointment/json",
    getAll: "appointments-slp/get-all-appointments",
    get: "appointments-slp/get-appointment",
    edit: "appointments-slp/edit-appointment/:appointmentId",
    getById: "appointments-slp/get-appointment-by-id",
    updateStatus: "appointments-slp/update-status/:appointmentId",
    getByClinician: "appointments-slp/get-appointment-by-clinician",
  },
  schedule: {
    create: "schedule-slp/add-schedule",
    get: "schedule-slp/get-schedules",
    edit: "schedule-slp/edit-schedule",
    delete: "schedule-slp/delete-schedule",
    clinician: "schedule-slp/clinician-schedules",
  },
};
